GET http://localhost:3000/products.json?category=Bikes
Content-Type: application/json
###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "electric scooter", 
  "price": "number", 
  "image_url": "jsfgosogj",
  "description": ""
}

### PRODUCTS UPDATES

PATCH http://localhost:3000/products/8.json
Content-Type: application/json

{ 
  "price": "number"
}

### delete

DELETE http://localhost:3000/products/5.json

### create user

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### sessions create (login)

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### login

GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUwMTQyODl9.iHZH8madtaHCyZINhu1mDHli9Hn2hsEU3xIWg-vAQmU
Content-Type: application/json

### order

POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNjg5ODh9.iJcstdDlqWCA1be6RNu5latwZtN-Gjvj0QBYfHevzyA
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 2
}

### ORDER INDEX

GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUyNzM4OTF9.FQ7NfXk61mwj3J8v-WLsHJGM1OlYGPgsOiJi4lp7gG4
Content-Type: application/json

### carted products create

POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzU1MzI1NjB9.ubapuTIQ0stnji4bTZviuRlHHSdClzngBMixfPcZDgo
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 1,
  "status": "carted",
  "order_id": 1
}

###

GET http://localhost:3000/carted_products.json